references_dir: 'references_dir'

# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.
include_references:
  - 'reference_configs/Drosophila_melanogaster.yaml'
  - 'reference_configs/ERCC.yaml'
  - 'reference_configs/PhiX.yaml'
  - 'reference_configs/Wolbachia_endosymbiont_of_Drosophila_melanogaster.yaml'
  - 'reference_configs/Homo_sapiens.yaml'
  - 'reference_configs/Saccharomyces_cerevisiae.yaml'
  - 'reference_configs/Schizosaccharomyces_pombe.yaml'
  - 'reference_configs/Mus_musculus.yaml'
  - 'reference_configs/Escherichia_coli.yaml'
  - 'reference_configs/Danio_rerio.yaml'